name: portfolio
version: 1.0.1

environment:
  sdk: ">=2.10.0-4.0.dev <3.0.0"
  flutter: ">=1.21.0-7.0.pre"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: 3.0.1
  provider: 4.0.4

  flutter_staggered_grid_view: 0.3.0
  animations: ^1.0.0+3

  url_launcher: ^5.4.1

dev_dependencies:
  pedantic: 1.9.0

  json_serializable: 3.2.5
  build_runner: 1.7.4

flutter:
  assets:
    - assets/avatar.png
    - assets/dart_pub.png
    - assets/github.png
    - assets/medium.png
    - assets/play_store.png
    - assets/reddit.png
    - assets/stackoverflow.png
    - assets/twitter.png
    - assets/web.png
    - assets/youtube.png
