name: portfolio
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^3.1.0
  provider: ^4.3.2

  flutter_staggered_grid_view: ^0.3.2
  animations: ^1.1.2

  url_launcher: ^5.7.2

dev_dependencies:
  pedantic: ^1.9.2

  json_serializable: ^3.5.0
  build_runner: ^1.10.3

flutter:
  assets:
    - assets/avatar.png
    - assets/dart_pub.png
    - assets/github.png
    - assets/medium.png
    - assets/play_store.png
    - assets/reddit.png
    - assets/stackoverflow.png
    - assets/twitter.png
    - assets/web.png
    - assets/youtube.png
