name: portfolio
version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: 3.0.1
  provider: 4.0.4

  url_launcher: ^5.4.1

dev_dependencies:
  pedantic: 1.9.0

  json_serializable: 3.2.5
  build_runner: 1.7.4

flutter:
  assets:
    - assets/dart_pub.png
    - assets/github.png
    - assets/medium.png
    - assets/play_store.png
    - assets/stackoverflow.png
    - assets/twitter.png
    - assets/web.png
    - assets/youtube.png
