name: portfolio
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.0.0
  provider: ^5.0.0

  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  animations: ^2.0.0

  url_launcher: ^6.0.2
  url_strategy: ^0.2.0

dev_dependencies:
  pedantic: ^1.11.0

  json_serializable: ^4.0.0
  build_runner: ^1.12.2

flutter:
  assets:
    - assets/avatar.png
    - assets/dart_pub.png
    - assets/github.png
    - assets/medium.png
    - assets/play_store.png
    - assets/reddit.png
    - assets/stackoverflow.png
    - assets/twitter.png
    - assets/web.png
    - assets/youtube.png
