name: portfolio
version: 1.0.0+1

environment:
  sdk: '>=2.16.0-0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.4.0
  provider: ^6.0.2

  flutter_staggered_grid_view: ^0.6.0
  animations: ^2.0.2

  url_launcher: ^6.0.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.4

  json_serializable: ^6.1.3
  build_runner: ^2.1.7

flutter:
  assets:
    - assets/avatar.png
    - assets/dart_pub.png
    - assets/github.png
    - assets/medium.png
    - assets/play_store.png
    - assets/reddit.png
    - assets/stackoverflow.png
    - assets/twitter.png
    - assets/web.png
    - assets/youtube.png
