name: web app

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/web_deploy.yml'
      - 'lib/**'
      - 'assets/**'
      - 'pubspec.yaml'

jobs:
  build:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    name: Web app deployment

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v1.3.2
        with:
          # Using the dev channel for now as Flutter web is not supported on stable yet.
          channel: 'dev'
          # Make sure to keep this up-to-date.
          flutter-version: '1.21.0-7.0.pre'

      - name: Build web app
        # Need to include the manually edited (migrated to non-nullable) generated file until
        # the generation package has been migrated to non-nullable.
        #          flutter packages pub run build_runner build
        run: |
          flutter pub get
          flutter config --enable-web
          flutter build web --release --enable-experiment=non-nullable --no-sound-null-safety
          cd build/web
          touch ".nojekyll"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
          GIT_CONFIG_NAME: creativecreatorormaybenot
          GIT_CONFIG_EMAIL: creativecreatorormaybenot@gmail.com
          COMMIT_MESSAGE: Deploy web app
