name: Web app

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/web_deploy.yml'
      - 'lib/**'
      - 'web/**'
      - 'assets/**'
      - 'pubspec.yaml'

jobs:
  deploy:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    name: Web app deployment

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'beta'

      - name: Build web app
        run: |
          flutter pub get
          flutter config --enable-web
          flutter packages pub run build_runner build
          flutter build web --no-sound-null-safety --web-renderer auto
          cd build/web
          touch ".nojekyll"
          echo "portfolio.creativemaybeno.dev" > CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
          GIT_CONFIG_NAME: creativecreatorormaybenot
          GIT_CONFIG_EMAIL: creativecreatorormaybenot@gmail.com
          COMMIT_MESSAGE: Deploy web app
